/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/login/LoginView': RouteRecordInfo<'/login/LoginView', '/login/LoginView', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/main/appointment/AppointmentView': RouteRecordInfo<'/main/appointment/AppointmentView', '/main/appointment/AppointmentView', Record<never, never>, Record<never, never>>,
    '/main/center/PersonalCenter': RouteRecordInfo<'/main/center/PersonalCenter', '/main/center/PersonalCenter', Record<never, never>, Record<never, never>>,
    '/main/class/MyClass': RouteRecordInfo<'/main/class/MyClass', '/main/class/MyClass', Record<never, never>, Record<never, never>>,
    '/main/laboratory/LaboratoryView': RouteRecordInfo<'/main/laboratory/LaboratoryView', '/main/laboratory/LaboratoryView', Record<never, never>, Record<never, never>>,
  }
}
